spring.application.name=backend
server.address=0.0.0.0
server.port=8080

# Tomorrow.io API Anahtarı
tomorrow.api.key=YOUR_TOMORROW_API_KEY_HERE(buraya kendi api keyinizi yazınız)

fastapi.base=http://127.0.0.1:8100

spring.cache.caffeine.spec=expireAfterWrite=15m